# Generated by Django 6.0 on 2026-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyPosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержимое",
                        null=True,
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="myblog/images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        help_text="Признак публикации",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(verbose_name="Количество просмотров"),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ["created_at"],
            },
        ),
    ]
