# Generated by Django 6.0 on 2026-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myposts",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
