# Generated by Django 6.0 on 2026-01-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_title",
            new_name="description",
        ),
    ]
